apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  replicas: 1
  revisionHistoryLimit: 1
  rollbackWindow:
    revisions: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: backend
        image: image_name
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
        startupProbe: # sleep between 5 and 10 seconds
          exec:
            command:
              - bash
              - -c
              - |-
                sleep $(( (RANDOM % 5) + 5 ))
          timeoutSeconds: 10
  strategy:
    canary:
      canaryService: preview
      stableService: stable
      scaleDownDelaySeconds: 3600
      scaleDownDelayRevisionLimit: 1
      maxSurge: 25%
      maxUnavailable: 0
      trafficRouting:
        nginx:
          stableIngress: backend-v3
      steps:
      - setWeight: 20
      - setCanaryScale: # scale replicaset to 100% with only 20% traffic
          weight: 100
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
