apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
spec:
  ingressClassName: nginx
  rules:
  - host: argo-rollouts-demo.dev.argoproj.io
    http:
      paths:
      - path: /gatekeeper
        pathType: Prefix
        backend:
          service:
            name: stable-gatekeeper-v3
            port:
              name: http
      - path: /one
        pathType: Prefix
        backend:
          service:
            name: stable-one-v3
            port:
              name: http
      - path: /two
        pathType: Prefix
        backend:
          service:
            name: stable-two-v3
            port:
              name: http
