apiVersion: batch/v1
kind: Job
metadata:
  name: job-022
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
    argocd.argoproj.io/sync-wave: '90'
spec:
  template:
    metadata:
      name: job-022
    spec:
      containers:
        - name: test
          image: alpine:latest
          command:
            - "bin/sh"
            - "-c"
            - "for i in 1 2 3 4 5 6 7 ; do echo $i ; done"
      restartPolicy: Never
