apiVersion: batch/v1
kind: Job
metadata:
  name: job-005
  annotations:
    argocd.argoproj.io/sync-wave: '90'
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      name: job-005
    spec:
      containers:
        - name: test
          image: alpine:latest
          command:
            - "bin/sh"
            - "-c"
            - "for i in 1 2 3 4 5 6 7 8 9 ; do echo $i ; done"
      restartPolicy: Never
