apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -v3

resources:
  - ./ingress.yaml
  - gatekeeper
  - one
  - two
  - three

images:
  - name: argoproj/rollouts-demo
    newTag: orange
