apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
spec:
  replicas: 3
  revisionHistoryLimit: 3
  # https://argo-rollouts.readthedocs.io/en/stable/features/rollback/
  rollbackWindow:
    revisions: 2
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
      - name: canary-demo
        image: ybelval/rollouts-demo:blue
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
        startupProbe: # sleep between 15 and 30 seconds
          exec:
            command:
              - bash
              - -c
              - |- 
                sleep $(( (RANDOM % 15) + 15 ))
          timeoutSeconds: 30
  strategy:
    canary:
      canaryService: canary-demo-preview
      stableService: canary-demo-stable
      scaleDownDelaySeconds: 3600
      scaleDownDelayRevisionLimit: 2
      trafficRouting:
        nginx:
          stableIngress: canary-demo
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
